source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'pushould-swift_Example', :exclusive => true do
  pod 'Socket.IO-Client-Swift', '~> 5.3.3'
  pod 'pushould-swift', :path => '../'
end

target 'pushould-swift_Tests', :exclusive => true do
  pod 'Socket.IO-Client-Swift', '~> 5.3.3'
  pod 'pushould-swift', :path => '../'

  pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
end
